# https://docs.nvidia.com/deeplearning/cudnn/v9.3.0/reference/support-matrix.html#cpu-architecture-and-os-requirements

arm_variant_type: # [linux and aarch64]
  - sbsa          # [linux and aarch64]
  - tegra         # [linux and aarch64]
c_stdlib_version:  # [linux]
  - 2.28           # [linux and aarch64]
  - 2.34           # [linux and aarch64]
  - 2.28           # [linux and x86_64]

zip_keys:               # [linux and aarch64]
  -                     # [linux and aarch64]
    - arm_variant_type  # [linux and aarch64]
    - c_stdlib_version  # [linux and aarch64]
